### ISSUE TITLE
ReactNode，function 需求

### ISSUE THREAD

**Issue by JIACHENG9** [smallfishjs/smallfish#21]
1. props 里可能有 ReactNode，比如

props:
```js
{
  a: {
    b: <Component title={<div>1</div>} />
  },
 a2: {
   name: '1'
 }
}
```

是否采用

```js
{
  a: {
    b: {
      type: 'react-node',
      name: 'button'
      props: {
        title: {
          type: 'react-node',
          name: 'div',
          props: {
            children: '1',
          }
        } 
      }
    }
  },
  a2: {
   name: '1'
  }
}
```

2. props 里可能有 () => ReactNode，比如:

props:
```js
{
  a: {
    b: (id) => <Button id={id} />
  }
}
```

是否采用

```js
{
  a: {
    b: {
      type: 'function-react-node',
      name: 'button',
      props: {
        id: '$params.0'
      }
    }
  }
}
```

**Comment by nikogu** [comment]
想了一下，多组件里面通过 props 传递组件的场景好像避免：

1. 因为在后台里面它存的数据，里面的参数有组件其实有点奇怪
2. 如果要渲染这个组件，是需要注册的，否则 schema 渲染的时候找不到，如果组件放到服务端传太灵活了
3. 如果一个组件需要用到传入组件的需求，最好是这个组件内部去做处理

从多组件来讲其实是可以避免的，因为我觉得目前这个 schema 只能描述组件的层级关系映射对应的 jsx，但是如果放到单个组件上说可能是需要的，如果是单个组件的需要的配置应该是另一套 json schema 的规范了。比如 form 的 schema 里面支持自定义的元素可能会用到。
