### ISSUE TITLE
why smallfish

### ISSUE THREAD

**Issue by JIACHENG9** [smallfishjs/smallfish#3]
### smallfish 是什么
smallfish 是基于 umi 的 React 前端框架，是由蚂蚁金服内部框架 bigfish 的发展出来的版本。

bigfish 是蚂蚁金服对内的企业级前端框架，提供强约定的开发方式，内置了配置式的路由、antd、dva 等，还包括了很多蚂蚁金服内部使用的插件，比如登录权限、发布等。bigfish 的底层最早的版本采用 webpack ，后来更改为了更为方便快捷的 umi。

bigfish 在内部有超过 1000+ 应用使用，有不少使用者是全栈开发，"清晰方便"，"约定配置"，"尽可能少的对底层的关注" 是其愿景，而 smallfish 正是承载了这一理念面向外部用户的一套方案。

#### 对比 bigfish
smallfish 可认为是 bigfish 对外使用的版本，有跟 bigfish 相同的理念，用户在整个开发周期只需要关注 smfllfish 即可：比如命令都是 smallfish dev，引入的包都是smllfish/antd 等，再也不用关心版本依赖以及框架选择问题，不过相对于 bigfish ，smallfish 的插件更加细粒度。

#### 对比 umi
umi 是一个非常优秀的前端框架，但是它面向的是广泛的应用场景和更加灵活的开发需求，smallfish 基于 umi 在配置、插件、约定、规范上进行了统一管理，目的就是强约束、重统一、轻使用。

一般场景下不需要关心插件的概念，对于开发者来说一切都是开关配置：

```js
export default {
  antdpro: true,
  styled: true,
  dva: true,
  i18n: true,
};
```

常用的包都被 smallfish 内置，告别版本依赖和选择困难症

```js
import React, { Component } from 'smallfish/react';
import { Steps, message } from 'smallfish/antd';
import { connect } from 'smallfish/dva';
import { PageHeader } from 'smallfish/ant-design-pro';
import { Link } from 'smallfish/router';
import styled from 'smallfish/styled';
import request from 'smallfish/request';
```

提供了一整套的规范：lint、国际化、目录规范等

### 插件
在 [smallfish 插件列表](https://www.npmjs.com/search?q=%40smallfish-plugin) 内置了smallfish 的插件（开发中）

不同的插件用户都能在 `config/config.js` 中选择关闭不使用。而高阶用户还能通过 `config/plugin.js`  使用自定义的其他功能，比如：

```js
export default [{
  pluginName: 自定义插件
  configName: 用户在 config.js 使用名称
  defaultOptions: 默认值，
}]
```

**Comment by ql434** [comment]
from bigfish
